### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by DZKeeper** [mwalkowski/anyrun#3]
Hi,

I dont know where I went wrong but I am getting the following last 3 lines of output:

`{'msg': 'nosub', 'id': 'tkvcdw8k', 'error': {'isClientSafe': True, 'error': 404, 'reason': "Subscription 'tasksHistoryCounter' not found", 'message': "Subscription 'tasksHistoryCounter' not found [404]", 'errorType': 'Meteor.Error'}}
{'msg': 'nosub', 'id': 'riuebghf', 'error': {'isClientSafe': True, 'error': 400, 'reason': 'Match failed', 'message': 'Match failed [400]', 'errorType': 'Meteor.Error'}}
{'msg': 'nosub', 'id': 'yk86mzr1', 'error': {'isClientSafe': True, 'error': 400, 'reason': 'Match failed', 'message': 'Match failed [400]', 'errorType': 'Meteor.Error'}}`

**Comment by mwalkowski** [comment]
Hi, thanks for the issue, I'll check it out in my free time today.

**Comment by DZKeeper** [comment]
I still seem to only get stats out of this, no tasks details. 

I noticed in the out I still get 1 line as follow:

`{'msg': 'nosub', 'id': 'q82n547x', 'error': {'isClientSafe': True, 'error': 400, 'reason': 'Match failed', 'message': 'Match failed [400]', 'errorType': 'Meteor.Error'}}`

could that be it ?
